/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlUsuario;
import Controlador.Main;
import Modelo.Usuario;
import Vista.Login.pnlRegistro;
import Vista.Preguntas.pnlPuntuaciones;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author PCSHOP
 */
public class FrmUsuario extends javax.swing.JFrame {

    CtlUsuario contronladorUsu;
    private final Usuario usu;

    /**
     * Creates new form FrmUsuario
     *
     * @param nombreUsu
     */
    public FrmUsuario(String nombreUsu) {
        initComponents();
        contronladorUsu = new CtlUsuario();
        lblEtiqueta.setText("<html>Te doy la bienvenida "
                + nombreUsu
                + "<br>realiza la accion que "
                + "desees<br>dando click "
                + "al boton de<br>la devida acción</html>");

        usu = contronladorUsu.traerUsuario(nombreUsu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlOpciones = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnPuntuaciones = new javax.swing.JButton();
        btnEditarPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        pnlCambio = new javax.swing.JPanel();
        pnlContenedorDialogo = new javax.swing.JPanel();
        lblEtiqueta = new javax.swing.JLabel();
        lblGif = new javax.swing.JLabel();
        lblNube = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrarVentana(evt);
            }
        });

        pnlContenedor.setBackground(new java.awt.Color(0, 0, 29));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOpciones.setBackground(new java.awt.Color(0, 0, 29));
        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPuntuaciones.setBackground(new java.awt.Color(153, 178, 203));
        btnPuntuaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPuntuaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnPuntuaciones.setText("Ver Puntuaciones");
        btnPuntuaciones.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnPuntuaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPuntuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuacionesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPuntuaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        btnEditarPerfil.setBackground(new java.awt.Color(153, 178, 203));
        btnEditarPerfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 100, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(153, 178, 203));
        btnCerrarSesion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 150, 60));

        btnJugar.setBackground(new java.awt.Color(153, 178, 203));
        btnJugar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(51, 51, 51));
        btnJugar.setText("Jugar");
        btnJugar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 100, 60));

        pnlOpciones.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        pnlCambio.setBackground(new java.awt.Color(0, 0, 29));

        javax.swing.GroupLayout pnlCambioLayout = new javax.swing.GroupLayout(pnlCambio);
        pnlCambio.setLayout(pnlCambioLayout);
        pnlCambioLayout.setHorizontalGroup(
            pnlCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCambioLayout.setVerticalGroup(
            pnlCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        pnlOpciones.add(pnlCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 480, -1));

        pnlContenedor.add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 480, -1));

        pnlContenedorDialogo.setBackground(new java.awt.Color(0, 0, 29));
        pnlContenedorDialogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEtiqueta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEtiqueta.setForeground(new java.awt.Color(255, 255, 255));
        lblEtiqueta.setText("Texto");
        pnlContenedorDialogo.add(lblEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/pinguino.gif"))); // NOI18N
        pnlContenedorDialogo.add(lblGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        lblNube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/icon.png"))); // NOI18N
        pnlContenedorDialogo.add(lblNube, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 290));

        pnlContenedor.add(pnlContenedorDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 528, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        // TODO add your handling code here:
        visualizar("registro");
        lblEtiqueta.setText("<html>Aqui Puedes modificar tu<br>información personal si no<br>sabes cuales son los campos solo<br>pon el mouse encima</html>");
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        lblEtiqueta.setText("  Adios " + usu.getNombreUsu() + "...");
        Main.mensaje(170, 30, "CERRANDO SESIÓN...", 3, "/Recursos/Imagenes/spinner-of-dots.png");
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPuntuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntuacionesActionPerformed
        // TODO add your handling code here:
        visualizar("");
        lblEtiqueta.setText("<html>Aqui Puedes visualizar tus<br>puntajes en las partidas<br>que has participado</html>");
    }//GEN-LAST:event_btnPuntuacionesActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main.mensaje(100, 30, "Cargando...", 3, "/Recursos/Imagenes/spinner-of-dots.png");
        FrmCrearJuego ventanaCrearJuego = new FrmCrearJuego(this);
        ventanaCrearJuego.setLocationRelativeTo(null);
        ventanaCrearJuego.setVisible(true);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void cerrarVentana(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarVentana
        // TODO add your handling code here:
        Main.mensaje(170, 30, "CERRANDO SESIÓN...", 3, "/Recursos/Imagenes/spinner-of-dots.png");
        cerrar();
    }//GEN-LAST:event_cerrarVentana


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPuntuaciones;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JLabel lblGif;
    private javax.swing.JLabel lblNube;
    private javax.swing.JPanel pnlCambio;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlContenedorDialogo;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOpciones;
    // End of variables declaration//GEN-END:variables

    //Metodo Para Visualizar Paneles
    public void visualizar(String panel) {
        try {
            pnlCambio.removeAll();
            JPanel panelNuevo;
            pnlCambio.setLayout(new BorderLayout(5, 5));
            if (panel.equalsIgnoreCase("registro")) {
                panelNuevo = new pnlRegistro(usu);
            } else {
                panelNuevo = new pnlPuntuaciones(usu.getCedula()+"");
            }
            pnlCambio.add(panelNuevo, BorderLayout.CENTER);
            pnlCambio.updateUI();
        } catch (ArrayIndexOutOfBoundsException e) {

        }
    }
    
    private void cerrar() {
        Main.abrirFrmPrincipal();
    }

    //Metodo Para Cambiar Cursor
    public void cambiarCursor(int cursor) {
        this.setCursor(cursor);
    }
}
