/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Login;

import Controlador.CtlJuego;
import Controlador.CtlUsuario;
import Controlador.Main;
import Vista.FrmAdministrador;
import Vista.FrmCrearJuego;
import Vista.FrmJuego;
import Vista.FrmUsuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Daryl Ospina
 */
public class pnlIniciarSesion extends javax.swing.JPanel {

    private String idJuego;
    private int participantes;
    CtlUsuario usu = new CtlUsuario();
    CtlJuego juego = new CtlJuego();
    public static ArrayList<String> listaCedulas = new ArrayList<String>();
    private JFrame padre;
    private CtlJuego controladorJuego;

    public pnlIniciarSesion() {
        initComponents();
        lblAstContraseña.setVisible(false);
        lblAstNombreUsu.setVisible(false);
        notaVisible(false);
        if (FrmCrearJuego.ventanaJuego == null) {
            recordarme();
        } else {
            chbRecordarme.setVisible(false);
        }
    }

    public pnlIniciarSesion(String idJuego, int participantes) {
        initComponents();
        controladorJuego = new CtlJuego();
        lblAstContraseña.setVisible(false);
        lblAstNombreUsu.setVisible(false);
        notaVisible(false);
        if (FrmCrearJuego.ventanaJuego == null) {
            recordarme();
        } else {
            chbRecordarme.setVisible(false);
        }
        this.idJuego = idJuego;
        this.participantes = participantes;
    }

    public pnlIniciarSesion(String idJuego, int participantes, JFrame padre) {
        initComponents();
        controladorJuego = new CtlJuego();
        lblAstContraseña.setVisible(false);
        lblAstNombreUsu.setVisible(false);
        notaVisible(false);
        if (FrmCrearJuego.ventanaJuego == null) {
            recordarme();
        } else {
            chbRecordarme.setVisible(false);
        }
        this.idJuego = idJuego;
        this.participantes = participantes;
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearCuenta = new javax.swing.JLabel();
        lblOlvideContraseña = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        chbRecordarme = new javax.swing.JCheckBox();
        txtContrasena = new javax.swing.JPasswordField();
        txtNombreUsu = new javax.swing.JTextField();
        lblNombreUsu = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblAstContraseña = new javax.swing.JLabel();
        lblAstNombreUsu = new javax.swing.JLabel();
        lblCampos = new javax.swing.JLabel();
        lblObligatorios = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 29));

        lblCrearCuenta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCrearCuenta.setForeground(new java.awt.Color(51, 153, 255));
        lblCrearCuenta.setText("Crear Cuenta");
        lblCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearCuentacambiarARegistro(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearCuentacambiarColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearCuentacambiarColor2(evt);
            }
        });

        lblOlvideContraseña.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblOlvideContraseña.setForeground(new java.awt.Color(51, 153, 255));
        lblOlvideContraseña.setText("¿Olvidaste Tu Contraseña?");
        lblOlvideContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvideContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOlvideContraseñacambiarColor3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOlvideContraseñacambiarColor4(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(204, 204, 204));
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        chbRecordarme.setBackground(new java.awt.Color(0, 0, 29));
        chbRecordarme.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chbRecordarme.setForeground(new java.awt.Color(255, 255, 255));
        chbRecordarme.setText("Recordarme");

        txtContrasena.setBackground(new java.awt.Color(51, 51, 51));
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusGained(evt);
            }
        });

        txtNombreUsu.setBackground(new java.awt.Color(51, 51, 51));
        txtNombreUsu.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreUsu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombreUsu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreUsuFocusGained(evt);
            }
        });

        lblNombreUsu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsu.setText("Nombre de usuario");

        lblContrasena.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/cropped-cropped-logoeam.png"))); // NOI18N

        lblAstContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/bloggif_59e7c9eb160c7.png"))); // NOI18N

        lblAstNombreUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/bloggif_59e7c9eb160c7.png"))); // NOI18N

        lblCampos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCampos.setForeground(new java.awt.Color(255, 255, 255));
        lblCampos.setText("Los Campos con asteriscos");

        lblObligatorios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblObligatorios.setForeground(new java.awt.Color(255, 255, 255));
        lblObligatorios.setText("son Obligatorios.");

        lblNota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNota.setForeground(new java.awt.Color(255, 0, 0));
        lblNota.setText("Nota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreUsu)
                            .addComponent(lblContrasena)
                            .addComponent(chbRecordarme)
                            .addComponent(txtNombreUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(txtContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAstNombreUsu)
                            .addComponent(lblAstContraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObligatorios)
                            .addComponent(lblCampos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblIcono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOlvideContraseña)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(lblCrearCuenta)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblAstNombreUsu)))
                .addGap(18, 18, 18)
                .addComponent(lblContrasena)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblAstContraseña)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbRecordarme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota)
                    .addComponent(lblCampos))
                .addGap(5, 5, 5)
                .addComponent(lblObligatorios)
                .addGap(29, 29, 29)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblOlvideContraseña)
                .addGap(18, 18, 18)
                .addComponent(lblCrearCuenta)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCrearCuentacambiarARegistro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentacambiarARegistro
        // TODO add your handling code here:
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.visualizar("registro");
        } else {
            FrmCrearJuego.ventanaJuego.visualizar("registro");
        }
    }//GEN-LAST:event_lblCrearCuentacambiarARegistro

    private void lblCrearCuentacambiarColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentacambiarColor
        // TODO add your handling code here:
        Main.ventanaPrincipal.cambiarColor(lblCrearCuenta, Color.yellow);
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.cambiarCursor(12);
        } else {
            FrmCrearJuego.ventanaJuego.cambiarCursor(12);
        }
    }//GEN-LAST:event_lblCrearCuentacambiarColor

    private void lblCrearCuentacambiarColor2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearCuentacambiarColor2
        // TODO add your handling code here:
        Main.ventanaPrincipal.cambiarColor(lblCrearCuenta, new Color(51, 153, 255));
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.cambiarCursor(0);
        } else {
            FrmCrearJuego.ventanaJuego.cambiarCursor(0);
        }
    }//GEN-LAST:event_lblCrearCuentacambiarColor2

    private void lblOlvideContraseñacambiarColor3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideContraseñacambiarColor3
        // TODO add your handling code here:
        Main.ventanaPrincipal.cambiarColor(lblOlvideContraseña, Color.yellow);
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.cambiarCursor(12);
        } else {
            FrmCrearJuego.ventanaJuego.cambiarCursor(12);
        }
    }//GEN-LAST:event_lblOlvideContraseñacambiarColor3

    private void lblOlvideContraseñacambiarColor4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideContraseñacambiarColor4
        // TODO add your handling code here:
        Main.ventanaPrincipal.cambiarColor(lblOlvideContraseña, new Color(51, 153, 255));
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.cambiarCursor(0);
        } else {
            FrmCrearJuego.ventanaJuego.cambiarCursor(0);
        }
    }//GEN-LAST:event_lblOlvideContraseñacambiarColor4

    private void lblOlvideContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvideContraseñaMouseClicked
        // TODO add your handling code here:
        if (Main.ventanaPrincipal.isActive()) {
            Main.ventanaPrincipal.visualizar("olvide");
        } else {
            FrmCrearJuego.ventanaJuego.visualizar("olvide");
            FrmCrearJuego.ventanaJuego.setSize(350, FrmCrearJuego.ventanaJuego.getHeight());
        }
    }//GEN-LAST:event_lblOlvideContraseñaMouseClicked

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            if (txtNombreUsu.getText().trim().equalsIgnoreCase("Admin") && txtContrasena.getText().trim().equalsIgnoreCase("123")) {
                FrmAdministrador admin = new FrmAdministrador();
                momentoIniciar(admin);
            } else if (Main.controUsuario.validarCampoUsuario(txtNombreUsu.getText().trim(), "nombreUsu", "usuario")) {
                if (Main.controUsuario.validarCampoUsuario(txtContrasena.getText().trim(), "contrasena", "usuario")) {
                    if (Main.ventanaPrincipal.isActive()) {
                        if (chbRecordarme.isSelected()) {
                            Main.controUsuario.eliminarRegistro();
                            Main.controUsuario.registroRecordar(txtNombreUsu.getText().trim(), txtContrasena.getText().trim());
                        }
                        FrmUsuario frmusu = new FrmUsuario(txtNombreUsu.getText() + "".trim());
                        momentoIniciar(frmusu);
                    } else {
                        String cedulaJugador = usu.traerDato(txtNombreUsu.getText().trim() + "", "cedula");
                        if (controladorJuego.validarJugador(cedulaJugador,idJuego)) {
                            listaCedulas.add(cedulaJugador);

                            FrmJuego jogo;
                            if (padre != null) {
                                jogo = new FrmJuego(idJuego, Integer.parseInt(usu.traerDato(txtNombreUsu.getText().trim() + "", "cedula")), participantes, padre);
                            } else {
                                jogo = new FrmJuego(idJuego, Integer.parseInt(usu.traerDato(txtNombreUsu.getText().trim() + "", "cedula")), participantes);
                            }
                            momentoIniciar(jogo);
                        }else{
                            JOptionPane.showMessageDialog(null, "Lo sentimos, no puede volver a jugar este juego");
                        }
                    }
                } else {
                    prevenirContrasena();
                }

            } else {
                cambiarNota("La informacion que ha diligenciado", "no es correcta o no existe");
                notaVisible(true);
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtNombreUsuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreUsuFocusGained
        // TODO add your handling code here:
        cambiarANormal(txtNombreUsu, lblAstNombreUsu);
    }//GEN-LAST:event_txtNombreUsuFocusGained

    private void txtContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusGained
        // TODO add your handling code here:
        cambiarANormal(txtContrasena, lblAstContraseña);
    }//GEN-LAST:event_txtContrasenaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JCheckBox chbRecordarme;
    private javax.swing.JLabel lblAstContraseña;
    private javax.swing.JLabel lblAstNombreUsu;
    private javax.swing.JLabel lblCampos;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCrearCuenta;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblObligatorios;
    private javax.swing.JLabel lblOlvideContraseña;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombreUsu;
    // End of variables declaration//GEN-END:variables

    //Metodos Para Obtener Los Campos Desde Otras Guis
    public JTextField getTxtNombreUsu() {
        return txtNombreUsu;
    }

    public JTextField getTxtContrasena() {
        return txtContrasena;
    }

    public JLabel getAstNombreUsu() {
        return lblAstNombreUsu;
    }

    public JLabel getAstContrasena() {
        return lblAstContraseña;
    }

    //Metodo Para Quitar El LineBorder Rojo
    public void cambiarANormal(JTextField txt, JLabel lbl) {
        EtchedBorder b = new EtchedBorder(1);
        txt.setBorder(b);
        lbl.setVisible(false);
        notaVisible(false);
        cambiarNota("Los Campos con asteriscos", "son Obligatorios.");
    }

    //Metodo Para Obtener Boolean Del CheckBox
    public boolean getRecordar() {
        return chbRecordarme.isSelected();
    }

    //Metodo Para Recordar
    public void recordar(boolean bool) {
        if (!bool) {
            txtNombreUsu.setText("");
            txtContrasena.setText("");
        }
    }

    //Metodo Para Validar Los Campos
    private boolean validar() {
        LineBorder b = new LineBorder(Color.red, 1);
        boolean bool = false;
        if (txtNombreUsu.getText().trim().isEmpty() || txtNombreUsu.getText().trim().equalsIgnoreCase("Nombre de usuario")) {
            txtNombreUsu.setBorder(b);
            lblAstNombreUsu.setVisible(true);
            bool = true;
        }
        if (txtContrasena.getText().trim().isEmpty() || txtContrasena.getText().trim().equalsIgnoreCase("Contraseña")) {
            txtContrasena.setBorder(b);
            lblAstContraseña.setVisible(true);
            bool = true;
        }
        return !notaVisible(bool);
    }

    //Metodo Para Cambiar El Mensaje De La Nota
    private void cambiarNota(String texto1, String texto2) {
        lblCampos.setText(texto1);
        lblObligatorios.setText(texto2);
    }

    //Metodo Para Mostar/Ocultar Etiqueta Espacios Obligatorios
    private boolean notaVisible(boolean bool) {
        lblNota.setVisible(bool);
        lblCampos.setVisible(bool);
        lblObligatorios.setVisible(bool);

        return bool;
    }

    //Iniciar Sesion
    private void momentoIniciar(JFrame frame) {
        Main.mensaje(100, 30, "Cargando...", 3, "/Recursos/Imagenes/spinner-of-dots.png");
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        if (Main.ventanaPrincipal.isVisible()) {
            recordar(chbRecordarme.isSelected());
            Main.ventanaPrincipal.setVisible(false);
        } else {
            FrmCrearJuego.ventanaJuego.setVisible(false);
        }
    }

    private void prevenirContrasena() {
        LineBorder b = new LineBorder(Color.red, 1);
        cambiarNota("El usuario que ha ingresado", "no coincide con la contraseña");
        notaVisible(true);
        txtContrasena.setBorder(b);
        lblAstContraseña.setVisible(true);
    }

    private void recordarme() {
        try {
            txtNombreUsu.setText(Main.controUsuario.mostrarRecordar().get(0));
            txtContrasena.setText(Main.controUsuario.mostrarRecordar().get(1));
        } catch (Exception e) {
        }
        if (!txtContrasena.getText().trim().isEmpty() && !txtNombreUsu.getText().trim().isEmpty()) {
            chbRecordarme.setSelected(true);
        }
    }
}
