/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Admin;

import Modelo.Pregunta;
import Modelo.Usuario;
import Vista.Login.pnlRegistro;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Daryl Ospina
 */
public class FrmPregUsu extends javax.swing.JDialog {

    /**
     * Creates new form FrmPregUsu1
     *
     * @param parent - sirve para mantener la ventana padre bloqueada
     * @param modal - para la herencia de frame si es true bloquea las demas
     * ventanas
     * @param index - sirve para transformar acciones como modificar y crear en
     * un mismo boton por ejemplo
     * @param padre - para llamar los metodos de otro frame del que este depende
     */
    public FrmPregUsu(java.awt.Frame parent, boolean modal, int index, JPanel padre) {
        super(parent, modal);
        initComponents();
        pnlContenedor.setLayout(new BorderLayout(5, 5));
        if (index == 0) {
            pnlContenedor.add(new pnlRegistro(true, this, padre));
        } else {
            pnlContenedor.add(new pnlPregun(this, padre));
        }
        pnlContenedor.updateUI();
    }

    public FrmPregUsu(Usuario usuario, java.awt.Frame parent, boolean modal, int index, JPanel padre) throws NullPointerException {
        super(parent, modal);
        initComponents();
        pnlContenedor.setLayout(new BorderLayout(5, 5));
        if (index == 0) {
            pnlContenedor.add(new pnlRegistro(usuario, true, this, padre));
        } else {
            pnlContenedor.add(new pnlPregun(this, padre));
        }
        pnlContenedor.updateUI();
    }

    public FrmPregUsu(Pregunta pregunta,String idPreg, java.awt.Frame parent, boolean modal, JPanel padre) throws NullPointerException {
        super(parent, modal);
        initComponents();
        pnlContenedor.setLayout(new BorderLayout(5, 5));
        pnlContenedor.add(new pnlPregun(pregunta,idPreg, this, padre));
        pnlContenedor.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
