/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Admin;

import Controlador.CtlTema;
import Controlador.Main;
import Modelo.Tema;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Daryl Ospina
 */
public class FrmTema extends javax.swing.JDialog {

    private CtlTema controladorTema;
    private String idTema;
    private Tema tema;
    private pnlPregUsus padre;

    /**
     * Creates new form FrmTema
     */
    public FrmTema(java.awt.Frame parent, boolean modal,JPanel padre) {
        super(parent, modal);
        initComponents();
        btn.requestFocus();
        lbl.setVisible(false);
        controladorTema = new CtlTema();
        this.padre = (pnlPregUsus)padre;
    }

    public FrmTema(String idTema,Tema tema, java.awt.Frame parent, boolean modal,JPanel padre)throws NullPointerException{
        super(parent, modal);
        initComponents();
        btn.requestFocus();
        lbl.setVisible(false);
        controladorTema = new CtlTema();
        this.idTema = idTema;
        this.tema = tema;
        btn.setText("MODIFICAR");
        this.padre = (pnlPregUsus)padre;
        txtNTema.setText(tema.getNombreTema());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn = new javax.swing.JButton();
        txtNTema = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 29));

        btn.setBackground(new java.awt.Color(51, 51, 51));
        btn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn.setForeground(new java.awt.Color(204, 204, 204));
        btn.setText("CREAR");
        btn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        txtNTema.setBackground(new java.awt.Color(51, 51, 51));
        txtNTema.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtNTema.setForeground(new java.awt.Color(204, 204, 204));
        txtNTema.setText("Nombre del tema");
        txtNTema.setToolTipText("Respuesta de seguridad");
        txtNTema.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNTema.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNTemaborrarRespuesta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNTemaponerRespuesta(evt);
            }
        });

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/bloggif_59e7c9eb160c7.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNTema, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNTema, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNTemaborrarRespuesta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNTemaborrarRespuesta
        // TODO add your handling code here:
        Main.ventanaPrincipal.vaciarCampo("Nombre del tema", txtNTema, Color.WHITE);
        lbl.setVisible(false);
    }//GEN-LAST:event_txtNTemaborrarRespuesta

    private void txtNTemaponerRespuesta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNTemaponerRespuesta
        // TODO add your handling code here:
        Main.ventanaPrincipal.vaciarCampo("Nombre del tema", txtNTema, Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtNTemaponerRespuesta

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        if (txtNTema.getText().isEmpty() || txtNTema.getText().equalsIgnoreCase("Nombre del tema")) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar Un Nombre Para El Tema");
            lbl.setVisible(true);
            txtNTema.setBorder(new LineBorder(Color.red));
        } else {
            if (tema == null) {
                Main.mensaje(300, 30, "CREANDO TEMA....", 3, "/Recursos/Imagenes/spinner-of-dots.png");
                if (controladorTema.registrar(txtNTema.getText().trim())) {
                    Main.mensaje(300, 30, "TEMA CREADO!!!", 3, "/Recursos/Imagenes/Cuenta.png");
                    this.dispose();
                    padre.listar();
                } else {
                    Main.mensaje(300, 30, "FALLO AL CREAR TEMA!!!", 3, "/Recursos/Imagenes/cancel.png");
                }
            }else{
                Main.mensaje(300, 30, "MODIFICANDO TEMA....", 3, "/Recursos/Imagenes/spinner-of-dots.png");
                if (controladorTema.modificar(txtNTema.getText().trim(),idTema)) {
                    Main.mensaje(300, 30, "TEMA MODIFICADO!!!", 3, "/Recursos/Imagenes/Cuenta.png");
                    padre.listar();
                    this.dispose();
                } else {
                    Main.mensaje(300, 30, "FALLO AL MODIFICAR TEMA!!!", 3, "/Recursos/Imagenes/cancel.png");
                }
            }
        }
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField txtNTema;
    // End of variables declaration//GEN-END:variables
}
