/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Admin;

import Controlador.CtlPregunta;
import Controlador.CtlTema;
import Controlador.Main;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Daryl Ospina
 */
public class pnlPregUsus extends javax.swing.JPanel {

    private final int modificador;
    private CtlPregunta controladorPreg;
    private CtlTema controladorTema;

    /**
     * Creates new form pnlPreguntas
     *
     * @param modificador
     */
    public pnlPregUsus(int modificador) {
        initComponents();
        this.modificador = modificador;
        switch (modificador) {
            case 0:
                tbl.setModel(Main.controUsuario.listar());
                btnInformacion.setVisible(false);
                break;
            case 1:
                controladorPreg = new CtlPregunta();
                tbl.setModel(controladorPreg.listarPreguntas());
                btnInformacion.setVisible(true);
                break;
            case 2:
                controladorTema = new CtlTema();
                tbl.setModel(controladorTema.listar());
                btnInformacion.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnUsuarios1 = new javax.swing.JButton();
        btnUsuarios2 = new javax.swing.JButton();
        btnUsuarios3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnInformacion = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 134, 150));

        btnUsuarios.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/add.png"))); // NOI18N
        btnUsuarios.setText("CREAR");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnUsuarios1.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios1.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/modify.png"))); // NOI18N
        btnUsuarios1.setText("MODIFICAR");
        btnUsuarios1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios1ActionPerformed(evt);
            }
        });

        btnUsuarios2.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios2.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/remove.png"))); // NOI18N
        btnUsuarios2.setText("ELIMINAR");
        btnUsuarios2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios2ActionPerformed(evt);
            }
        });

        btnUsuarios3.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios3.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/update.png"))); // NOI18N
        btnUsuarios3.setText("ACTUALIZAR TABLA");
        btnUsuarios3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 134, 150));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        btnInformacion.setBackground(new java.awt.Color(75, 117, 137));
        btnInformacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInformacion.setForeground(new java.awt.Color(0, 0, 29));
        btnInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/information-button.png"))); // NOI18N
        btnInformacion.setText("INFORMACIÓN DE PREGUNTA");
        btnInformacion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        JDialog ventana;
        switch (modificador) {
            case 0:
                ventana = new FrmPregUsu(null, true, 0, this);
                break;
            case 1:
                ventana = new FrmPregUsu(null, true, 1, this);
                break;
            case 2:
                ventana = new FrmTema(null, true, this);
                break;
            default:
                return;
        }
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios1ActionPerformed
        // TODO add your handling code here:
        JDialog ventana;
        if (tbl.getSelectedRow() == -1) {
            switch (modificador) {
                case 0:
                    String cedula = JOptionPane.showInputDialog("Ingrese La Cedula Del Usuario Que Desea Modificar");
                    if (cedula != null) {
                        try {
                            ventana = new FrmPregUsu(Main.controUsuario.traerUsuario(Integer.parseInt(cedula)), null, true, 0, this);
                        } catch (NullPointerException | NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "No ha ingresado una cedula valida");
                            return;
                        }
                    } else {
                        return;
                    }
                    break;
                case 1:
                    String idPreg = JOptionPane.showInputDialog("Ingrese el numero de la pregunta que desea modificar");
                    if (idPreg != null) {
                        try {
                            ventana = new FrmPregUsu(controladorPreg.traerPregunta(Integer.parseInt(idPreg)), idPreg, null, true, this);
                        } catch (NullPointerException | NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "No ha ingresado un numero de pregunta valida");
                            return;
                        }
                    } else {
                        return;
                    }
                    break;
                case 2:
                    String idTema = JOptionPane.showInputDialog("Ingrese el numero del tema que desea modificar");
                    if (idTema != null) {
                        try {
                            ventana = new FrmTema(idTema, controladorTema.traerTema(idTema), null, true, this);
                        } catch (NullPointerException | NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "No ha ingresado un numero de tema valido");
                            return;
                        }
                    } else {
                        return;
                    }
                    break;
                default:
                    return;
            }
        } else {
            switch (modificador) {
                case 0:
                    ventana = new FrmPregUsu(Main.controUsuario.traerUsuario((int) tbl.getValueAt(tbl.getSelectedRow(), 0)), null, true, 0, this);
                    break;
                case 1:
                    ventana = new FrmPregUsu(controladorPreg.traerPregunta(
                            Integer.parseInt(tbl.getValueAt(tbl.getSelectedRow(), 0) + "")),
                            tbl.getValueAt(tbl.getSelectedRow(), 0) + "", null, true, this);
                    tbl.setModel(controladorPreg.listarPreguntas());
                    break;
                case 2:
                    ventana = new FrmTema(tbl.getValueAt(tbl.getSelectedRow(), 0) + "", controladorTema.traerTema(tbl.getValueAt(tbl.getSelectedRow(), 0) + ""), null, true, this);
                    tbl.setModel(controladorTema.listar());
                    break;
                default:
                    return;
            }
        }
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuarios1ActionPerformed

    private void btnUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios2ActionPerformed
        // TODO add your handling code here:
        if (tbl.getSelectedRow() == -1) {
            switch (modificador) {
                case 0:
                    String cedula = JOptionPane.showInputDialog("Ingrese La Cedula Del Usuario Que Desea Eliminar");
                    if (cedula != null) {
                        if (Main.controUsuario.solicitarEliminar(cedula)) {
                            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro el usuario");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No ha ingresado nada");
                    }
                    tbl.setModel(Main.controUsuario.listar());
                    break;
                case 1:
                    String idPregunta = JOptionPane.showInputDialog("Ingrese el numero de la pregunta Que Desea Eliminar");
                    if (idPregunta != null) {
                        if (controladorPreg.eliminarPregunta(Integer.parseInt(idPregunta))) {
                            JOptionPane.showMessageDialog(null, "Pregunta Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro la pregunta");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No ha ingresado nada");
                    }
                    tbl.setModel(controladorPreg.listarPreguntas());
                    break;
                case 2:
                    String idTema = JOptionPane.showInputDialog("Ingrese el numero del tema que desea Eliminar");
                    if (idTema != null) {
                        if (controladorTema.eliminar(idTema)) {
                            JOptionPane.showMessageDialog(null, "Tema Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro el tema");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No ha ingresado nada");
                    }
                    tbl.setModel(controladorTema.listar());
                    break;
            }
        } else {
            int desicion;
            switch (modificador) {
                case 0:
                    String cedula = tbl.getValueAt(tbl.getSelectedRow(), 0) + "";
                    desicion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el usuario con la cedula: " + cedula);
                    if (desicion == 0) {
                        if (Main.controUsuario.solicitarEliminar(cedula)) {
                            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro el usuario");
                        }
                        tbl.setModel(Main.controUsuario.listar());
                    }
                    break;
                case 1:
                    String idPregunta = tbl.getValueAt(tbl.getSelectedRow(), 0) + "";
                    desicion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar la pregunta numero: " + idPregunta);
                    if (desicion == 0) {
                        if (controladorPreg.eliminarPregunta(Integer.parseInt(idPregunta))) {
                            JOptionPane.showMessageDialog(null, "Pregunta Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro la pregunta");
                        }
                        tbl.setModel(controladorPreg.listarPreguntas());
                    }
                    break;
                case 2:
                    String idTema = tbl.getValueAt(tbl.getSelectedRow(), 0) + "";
                    desicion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el tema numero: " + idTema);
                    if (desicion == 0) {
                        if (controladorTema.eliminar(idTema)) {
                            JOptionPane.showMessageDialog(null, "Tema Eliminado");
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontro el tema");
                        }
                        tbl.setModel(controladorTema.listar());
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btnUsuarios2ActionPerformed

    private void btnUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios3ActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnUsuarios3ActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        FrmInfoPreguntra pregunta;
        String id;
        if (tbl.getSelectedRow() == -1) {
            id = JOptionPane.showInputDialog("Ingrese el id de la pregunta que desea ver la informacion");
            if (id != null) {
                try {

                    if (id.equalsIgnoreCase("")) {
                        JOptionPane.showMessageDialog(this, "Por favor llene el campo");
                    }
                    if (controladorPreg.validarPreguntar(id)) {
                        pregunta = new FrmInfoPreguntra(id);
                        pregunta.setVisible(true);
                        pregunta.setLocationRelativeTo(null);

                    } else {
                        JOptionPane.showMessageDialog(this, "El id ingresado no existe");
                    }
                } catch (NullPointerException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "No ha ingresado un numero de pregunta valida");
                }
            }
        } else {
            pregunta = new FrmInfoPreguntra(tbl.getValueAt(tbl.getSelectedRow(), 0) + "");
            pregunta.setVisible(true);
            pregunta.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnInformacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnUsuarios1;
    private javax.swing.JButton btnUsuarios2;
    private javax.swing.JButton btnUsuarios3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    public void listar() {
        switch (modificador) {
            case 0:
                tbl.setModel(Main.controUsuario.listar());
                break;
            case 1:
                tbl.setModel(controladorPreg.listarPreguntas());
                break;
            case 2:
                tbl.setModel(controladorTema.listar());
                break;
        }
    }
}
